from enum import Enum

class ProcessType(Enum):
    EXPLORATION_DATA_ANALYSIS = 'EXPLORATION_DATA_ANALYSIS'
    TRAIN_EVALUATE = 'TRAIN_EVALUATE'
    TRAIN_AND_EVALUATE_INDIVIDUAL_SERIES = 'TRAIN_AND_EVALUATE_INDIVIDUAL_SERIES'
    SELECT_MODEL = 'SELECT_MODEL'
    FINAL_PREDICT = 'FINAL_PREDICT'